main/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls import include

admin.autodiscover()
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^teacherPlan/', include('teacherPlan.urls')),
]

teacherPlan/urls.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from django.conf.urls import url, include
from django.contrib.contenttypes import views as contenttype_views
from views import *

urlpatterns = patterns(
   '',
   url(r'^$', index, name='tpindex'),

   #auth
   url(r'^login$', loginTeacher, name='tplogin', ),
   url(r'^loginwitherror$', errorLoginTeacher, name='tploginwitherror', ),
   url(r'^logout$', logoutTeacher, name='tplogout', ),
   url(r'^registerTeacher/', registerTeacher, name='registerTeacher' ),

   #Property
   url('^editProperty/', editPropertySite, name='editProperty'),


   #plans
   url(r'^listOfPlans$', listOfPlans, name='tpplanlist', ),
   url(r'^plan/(?P<id>[0-9a-z]+)$', plan, name='tpplan', ),
   url(r'^currentPlan/', currentPlan, name='currentPlan', ),
   url(r'^plan/add/',makeNewPlan , name='addPlan'),
   url(r'^plan/edit/(?P<id>[0-9a-z]+)$',editPlan , name='editPlan'),
   url(r'^plan/deletePlan/(?P<id>[0-9a-z]+)$',deletePlan , name='deletePlan'),
   url(r'^allplans/', show_all_plan, name='showAllPlans'),



   #forms_edit
   url(r'^studybookList/(?P<id>[0-9a-z]+)/edit', studybook_list_edit, name='studybookListEdit'),
   url(r'^disciplineList/(?P<id>[0-9a-z]+)/edit', discipline_list_edit, name='disciplineListEdit'),
   url(r'^scWorkList/(?P<id>[0-9a-z]+)/edit', scWorkList_edit, name='scWorkListEdit'),
   url(r'^participationList/(?P<id>[0-9a-z]+)/edit', participation_list_edit, name='participationListEdit'),
   url(r'^publicationList/(?P<id>[0-9a-z]+)/edit', publication_list_edit, name='publicationListEdit'),
   url(r'^qualificationList/(?P<id>[0-9a-z]+)/edit', qualification_list_edit, name='qualificationListEdit'),
   url(r'^difWorkList/(?P<id>[0-9a-z]+)/edit', dif_work_list_edit, name='difWorkListEdit'),

   #forms
   url(r'^studybookList/(?P<id>[0-9a-z]+)', studybook_list, name='studybookList'),
   url(r'^disciplineList/(?P<id>[0-9a-z]+)', discipline_list, name='disciplineList'),
   url(r'^scWorkList/(?P<id>[0-9a-z]+)', scWorkList, name='scWorkList'),
   url(r'^participationList/(?P<id>[0-9a-z]+)', participation_list, name='participationList'),
   url(r'^publicationList/(?P<id>[0-9a-z]+)', publication_list, name='publicationList'),
   url(r'^qualificationList/(?P<id>[0-9a-z]+)', qualification_list, name='qualificationList'),
   url(r'^difWorkList/(?P<id>[0-9a-z]+)', dif_work_list, name='difWorkList'),

   url(r'^pdf/(?P<id>[0-9a-z]+)', makePDF, name='pdf'),
)

moevmCommon/models.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.forms import forms
from django.utils.encoding import python_2_unicode_compatible
from djangotoolbox.fields import EmbeddedModelField
from djangotoolbox.fields import ListField


def filter_by_foreign_fields(model_manager, **filter_fields):

    def filter_condition(model):

        if not hasattr(model, 'user'):
            return False

        model_fields = model.__dict__.items()
        user_fields = model.user.__dict__.items()

        # merge model and user field dicts
        fields = dict(model_fields + user_fields +
                      [(k, model_fields[k] + user_fields[k])
                       for k in set(model_fields) & set(user_fields)])

        for arg_name, arg_value in filter_fields.items():
            if arg_name not in fields:
                continue

            if arg_value != fields[arg_name]:
                return False

        return True

    return list(filter(filter_condition, model_manager.all()))

@python_2_unicode_compatible
class UserProfileManager(models.Manager):
    # Для фильтрации по внешнему ключу UserProfile
    #def filter(self, **filter_fields):
    #   return filter_by_foreign_fields(super(UserProfileManager, self), **filter_fields)
    
    def create_all(self, username,
               password, email,
               **kwargs):

        user = User(username=username, email=email, password=password)

        user.first_name = kwargs.get('first_name')
        user.last_name = kwargs.get('last_name')
        user.is_superuser = kwargs.get('is_superuser', False)
        user.save()
        print "hell"
        return self.create(
            user=user,
            patronymic=kwargs.get('patronymic'),
            birth_date=kwargs.get('birth_date'),
            study_group=kwargs.get('study_group'),
            github_id=kwargs.get('github_id'),
            stepic_id=kwargs.get('stepic_id'),
            role=kwargs.get('role', 's'),
            election_date=kwargs.get('election_date'),
            position=kwargs.get('position'),
            contract_date=kwargs.get('contract_date'),
            academic_degree=kwargs.get('academic_degree'),
            year_of_academic_degree=kwargs.get('year_of_academic_degree'),
            academic_status=kwargs.get('academic_status'),
            year_of_academic_status=kwargs.get('year_of_academic_status')
        )

    def create_student(self,
                       username=None,
                       email=None,
                       password=None,
                       first_name=None,
                       last_name=None,
                       birth_date=None,
                       patronymic=None,
                       study_group=None,
                       github_id=None,
                       stepic_id=None,
                       **kwargs):
      user = User(username=username, email=email, password=password)

      user.first_name = first_name
      user.last_name = last_name
      user.is_superuser = False
      user.save()
      type = "s"
      return self.create(
        user=user,
        patronymic=patronymic,
        birth_date=birth_date,
        study_group=study_group,
        github_id=github_id,
        stepic_id=stepic_id,
        type=type
      )

    def create_head_student(self,
                       username=None,
                       email=None,
                       password=None,
                       first_name=None,
                       last_name=None,
                       birth_date=None,
                       patronymic=None,
                       study_group=None,
                       github_id=None,
                       stepic_id=None,
                       **kwargs):
      user = User(username=username, email=email, password=password)
      user.first_name = first_name
      user.last_name = last_name
      user.is_superuser = False
      user.save()
      type = "h"
      return self.create(
        user=user,
        patronymic=patronymic,
        birth_date=birth_date,
        study_group=study_group,
        github_id=github_id,
        stepic_id=stepic_id,
        type=type
      )

    def create_teacher(self,
                       username=None,
                       email=None,
                       password=None,
                       first_name=None,
                       last_name=None,
                       birth_date=None,
                       patronymic=None,
                       election_date=None,
                       position=None,
                       contract_date=None,
                       academic_degree=None,
                       year_of_academic_degree=None,
                       academic_status=None,
                       year_of_academic_status=None,
                       academic_state=None,
                       rate=None,
                       github_id=None,
                       stepic_id=None,
                       **kwargs):
      user = User(username=username, email=email, password=password)
      user.first_name = first_name
      user.last_name = last_name
      user.is_superuser = False
      user.save()
      type = "t"
      return self.create(
        user=user,
        patronymic=patronymic,
        birth_date=birth_date,
        election_date=election_date,
        github_id=github_id,
        stepic_id=stepic_id,
        position=position,
        rate=rate,
        contract_date=contract_date,
        academic_degree=academic_degree,
        year_of_academic_degree=year_of_academic_degree,
        academic_status=academic_status,
        year_of_academic_status=year_of_academic_status,
        academic_state=academic_state,
        type=type
      )


    def create_from_user(self,
                         user=None,
                         position=None,
                         contract_date=None,
                         academic_degree=None,
                         year_of_academic_degree=None,
                         academic_status=None,
                         patronymic=None,
                         **params):
        return  self.create(
            user=user,
            patronymic=patronymic,
            type=type,
            position=position,
            contract_date=contract_date,
            academic_degree=academic_degree,
            year_of_academic_degree=year_of_academic_degree,
            academic_status=academic_status,
        )

    def __str__(self):
      return 'UserProfileManager'

PERSON_TYPE_CHOICES = (
    ('s', 'Студент'),
    ('h', 'Староста'),
    ('t', 'Преподаватель'),
    ('a', 'Администратор'),
)
ACADEMIC_STATUS_CHOICES  = (
  ('a','Ассистент'),
  ('s','Старший преподаватель'),
  ('d','Доцент'),
  ('p','Профессор'),
)
ACADEMIC_DEGREE_CHOICES = (
  ('n','Без степени'),
  ('t','Кандидат наук'),
  ('d','Доктор наук'),
)
ACADEMIC_STATE_CHOICES  = (
  ('a', 'Аспирант'),
  ('d', 'Докторант'),
  ('s', 'Соискатель'),
  ('st', 'Стажер'),
)
RATE_CHOICES = (
    ('1', '0,25 ставки'),
    ('2', '0,5 ставки'),
    ('3', '0,75 ставки'),
    ('4', '1 ставки'),
)

@python_2_unicode_compatible
class UserProfile(models.Model):
    user = models.OneToOneField(
        User,
        verbose_name="Ссылка на аккаунт для авторизации",
    )

    patronymic = models.CharField(
        max_length=30,
        null=True,
        verbose_name="Отчество",
        blank=True,
    )
    birth_date = models.DateField(
        null=True,
        verbose_name="Дата рождения",
        blank=True,
    )
    study_group = models.CharField(
        max_length=5,
        null=True,
        verbose_name="Учебная группа",
        blank=True,
    )
    github_id = models.CharField(
        max_length=100,
        null=True,
        verbose_name="Профиль github",
        blank=True,
    )
    stepic_id = models.CharField(
        max_length=100,
        null=True,
        verbose_name="Профиль stepic",
        blank=True,
    )

    type = models.CharField(
        max_length=2,
        choices=PERSON_TYPE_CHOICES,
        default='s',
        verbose_name="Тип",
    )

    election_date = models.DateField(
        null=True,
        verbose_name="Дата текущего избрания или зачисления на преподавательскую должность",
        blank=True,
    )

    position = models.CharField(
        max_length=40,
        null=True,
        verbose_name="Должность",
        blank=True,
    )

    contract_date = models.DateField(
        null=True,
        blank=True,
        verbose_name="Срок окончания трудового договора",
    )

    academic_degree = models.CharField(
        max_length=1,
        choices=ACADEMIC_DEGREE_CHOICES,
        null=True,
        verbose_name="Ученая степень",
        blank=True,
    )

    year_of_academic_degree = models.IntegerField(
        null=True,
        verbose_name="Год присвоения ученой степени",
        blank=True,
    )

    academic_status = models.CharField(
        max_length=1,
        choices=ACADEMIC_STATUS_CHOICES,
        null=True,
        verbose_name="Учебное звание",
        blank=True,
    )

    year_of_academic_status = models.IntegerField(
        null=True,
        verbose_name="Год получения учебного звания",
        blank=True,
    )

    rate = models.CharField(
        max_length=1,
        choices=RATE_CHOICES,
        null=True,
        verbose_name="Ставка",
        blank=True,
    )

    academic_state = models.CharField(
        max_length=1,
        choices=ACADEMIC_STATE_CHOICES,
        null=True,
        verbose_name="Академическое положение",
        blank=True,
    )

    objects = UserProfileManager()

    @property
    def first_name(self):
        return self.user.first_name

    @property
    def last_name(self):
        return self.user.last_name

    @property
    def login(self):
        return self.user.username

    @property
    def password(self):
        return self.user.password

    @property

teacherPlan/models.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from djangotoolbox.fields import EmbeddedModelField, ListField

@python_2_unicode_compatible
class TeacherSettings(models.Model):
    department_name = models.CharField(
        verbose_name="Название кафедры",
        max_length=10,
        null=True,
        blank=True,
    )
    organisation_name = models.CharField(
        verbose_name="Название факультета",
        max_length=10,
        null=True,
        blank=True,
    )
    department_head = models.CharField(
        verbose_name="Заведующий кафедры",
        max_length=100,
        null=True,
        blank=True,
    )
    organisation_head = models.CharField(
        verbose_name="Декан",
        max_length=100,
        null=True,
        blank=True,
    )
    @staticmethod
    def get():
        try:
            return TeacherSettings.objects.first()
        except:
            return TeacherSettings.objects.create(
                department_name=u"Кафедра",
                organisation_name=u"Факультет",
                department_head=u"Зав. Кафедры",
                organisation_head=u"Декан",
            )

    def __str__(self):
        return u"Основные настройки"

teacherPlan/templates/teacherPlan/forms/update/1_studybook_list.html
{% extends 'teacherPlan/pages/template.html' %}
{% block title %}Редактирование сведений об учебных материалах{% endblock %}
{% block pagename %}Редактирование сведений об учебных материалах{% endblock %}
{% block content %}
    <a type="button" href="{% url 'tpplan' planid %}">Назад к плану</a>
    {% if form.errors %}
        <p class="bg-danger text-danger">
            Ошибка при заполнении формы.
        </p>
    {% endif %}

    <form action="#" method="post">
        {% csrf_token %}
        <p><label for="id_name">Наименование:</label>
            <input id="id_name" maxlength="200" name="name" type="text" value="{{ target.name }}"></p>
        <p><label for="id_type">Вид издания:</label>
            <input id="id_type" maxlength="200" name="type" type="text"  value="{{ target.type }}"></p>
        <p><label for="id_volume">Объем в п.л.</label>
            <input id="id_volume" min="0" name="volume" type="number"  value="{{ target.volume }}"></p>
        <p><label for="id_vulture">Вид грифа:</label>
            <input id="id_vulture" maxlength="200" name="vulture" type="text"  value="{{ target.vulture }}"></p>
        <p><label for="id_finishDate">Срок сдачи рукописи:</label>
            <input id="id_finishDate" min="0" name="finishDate" type="number" value="{{ target.finishDate }}"></p>
        <input type="hidden" name="idlink" value="{{ idlink }}">
        <input type="submit" value="Изменить">
    </form>
    <br>
    <a type="button" class="btn btn-primary" href="{% url 'studybookList' planid %}">Отмена</a>
{% endblock %}

teacherPlan/templates/teacherPlan/forms/update/2_discipline_list.html
{% extends 'teacherPlan/pages/template.html' %}
{% block title %}Редактирование сведений о преподаваемых дисциплинах{% endblock %}
{% block pagename %}Редактирование сведений о преподаваемых дисциплинах{% endblock %}
{% block content %}
    <a type="button" href="{% url 'tpplan' planid %}">Назад к плану</a>
    {% if form.errors %}
        <p class="bg-danger text-danger">
            Ошибка при заполнении формы.
        </p>
    {% endif %}

    <form action="#" method="post">
        {% csrf_token %}
        <p><label for="id_name">Наименование дисциплины:</label>
            <input id="id_name" maxlength="200" name="name" type="text" value="{{ target.name }}"></p>
        <p><label for="id_type">Вид занятия:</label>
            <input id="id_type" maxlength="200" name="type" type="text"  value="{{ target.type }}"></p>
        <p><label for="id_characterUpdate">Характер изменения:</label>
            <input id="id_characterUpdate" maxlength="200" name="characterUpdate" type="text"  value="{{ target.characterUpdate }}"></p>
        <input type="hidden" name="idlink" value="{{ idlink }}">
        <input type="submit" value="Изменить">
    </form>
    <br>
    <a type="button" class="btn btn-primary" href="{% url 'disciplineList' planid %}">Отмена</a>
{% endblock %}

teacherPlan/templates/teacherPlan/forms/update/3_sc_work_list.html
{% extends 'teacherPlan/pages/template.html' %}
{% block title %}Редактирование сведений о научной работе{% endblock %}
{% block pagename %}Редактирование сведений о научной работе{% endblock %}
{% block content %}
    <a type="button" href="{% url 'tpplan' planid %}">Назад к плану</a>
    {% if form.errors %}
        <p class="bg-danger text-danger">
            Ошибка при заполнении формы.
        </p>
    {% endif %}

    <form action="#" method="post">
        {% csrf_token %}
        <p><label for="id_name">Наименование работы:</label>
            <input id="id_name" maxlength="200" name="name" type="text" value="{{ target.name }}"></p>
        <p><label for="id_period">Период:</label>
            <input id="id_period" maxlength="200" name="period" type="text" value="{{ target.period }}"></p>
        <p><label for="id_role">В качестве кого участвовал:</label>
            <input id="id_role" maxlength="200" name="role" type="text" value="{{ target.role }}"></p>
        <p><label for="id_organisation">Организация или предприятие:</label>
            <input id="id_organisation" maxlength="200" name="organisation" type="text" value="{{ target.organisation }}"></p>
        <input type="hidden" name="idlink" value="{{ idlink }}">
        <input type="submit" value="Изменить">
    </form>
    <br>
    <a type="button" class="btn btn-primary" href="{% url 'scWorkList' planid %}">Отмена</a>
{% endblock %}

teacherPlan/templates/teacherPlan/forms/update/4_participation_list.html
{% extends 'teacherPlan/pages/template.html' %}
{% block title %}Редактирование сведений об участии в конкурсе{% endblock %}
{% block pagename %}Редактирование сведений об участии в конкурсе{% endblock %}
{% block content %}
    <a type="button" href="{% url 'tpplan' planid %}">Назад к плану</a>
    {% if form.errors %}
        <p class="bg-danger text-danger">
            Ошибка при заполнении формы.
        </p>
    {% endif %}

    <form action="#" method="post">
        {% csrf_token %}
        <p><label for="id_name">Наименование конференции:</label>
            <input id="id_name" maxlength="200" name="name" type="text" value="{{ target.name }}"></p>
        <p><label for="id_level">Уровень конференции:</label>
            <input id="id_level" maxlength="200" name="level" type="text" value="{{ target.level }}"></p>
        <p><label for="id_report">Наименование доклада:</label>
            <input id="id_report" maxlength="200" name="report" type="text" value="{{ target.report }}"></p>
        <p><label for="id_date">Дата:</label>
            <input id="id_date" maxlength="30" name="date" type="text" value="{{ target.date }}"></p>
        <input type="hidden" name="idlink" value="{{ idlink }}">
        <input type="submit" value="Изменить">
    </form>
    <br>
    <a type="button" class="btn btn-primary" href="{% url 'participationList' planid %}">Отмена</a>
{% endblock %}

teacherPlan/templates/teacherPlan/forms/update/5_publication_list.html
{% extends 'teacherPlan/pages/template.html' %}
{% block title %}Список публикаций{% endblock %}
{% block pagename %}Список публикаций{% endblock %}
{% block content %}
    <a type="button" href="{% url 'tpplan' planid %}">Назад к плану</a>
    {% if form.errors %}
        <p class="bg-danger text-danger">
            Ошибка при заполнении формы.
        </p>
    {% endif %}

    <form action="#" method="post">
        {% csrf_token %}
        <p><label for="id_name_work">Наименование работ:</label>
            <input id="id_name_work" maxlength="200" name="name_work" type="text" value="{{ publ.name_work }}"></p>
        <p><label for="id_type">Вид публикации:</label>
            <input id="id_type" maxlength="200" name="type" type="text" value="{{ publ.type }}"></p>
        <p><label for="id_volume">Объем в п.л.</label>
            <input id="id_volume" min="0" name="volume" type="number" value="{{ publ.volume }}"></p>
        <p><label for="id_name_publisher">Наименование издательства:</label>
            <input id="id_name_publisher" maxlength="200" name="name_publisher" type="text"
                   value="{{ publ.name_publisher }}"></p>
        <input type="hidden" name="idlink" value="{{ idlink }}">
        <input type="submit" value="Изменить">
    </form>
    <br>
    <a type="button" class="btn btn-primary" href="{% url 'publicationList' planid %}">Отмена</a>
{% endblock %}

teacherPlan/templates/teacherPlan/forms/update/6_qualification_list.html
{% extends 'teacherPlan/pages/template.html' %}
{% block title %}Редактирование сведений о "повышение  квалификации"{% endblock %}
{% block pagename %}Редактирование сведений о "повышение  квалификации"{% endblock %}
{% block content %}

    <a type="button" href="{% url 'tpplan' planid %}">Назад к плану</a>
        {% if form.errors %}
        <p class="bg-danger text-danger">
            Ошибка при заполнении формы.
        </p>
    {% endif %}

    <form action="#" method="post">
        {% csrf_token %}
         <p><label for="id_period">Период:</label>
             <input id="id_period" maxlength="20" name="period" type="text" value="{{ qualification.period }}"></p>
         <p><label for="id_form_training">Форма повышения квалификации:</label>
             <input id="id_form_training" maxlength="200" name="form_training" type="text"
                    value="{{ qualification.form_training }}"></p>
         <p><label for="id_document">Документ:</label>
             <input id="id_document" maxlength="200" name="document" type="text"
             value="{{ qualification.document }}"></p>
        <input type="hidden" name="idqual" value="{{ idqual }}">
        <input type="submit" value="Изменить">
    </form>
    <br>
    <a type="button" class="btn btn-primary" href="{% url 'qualificationList' planid %}">Отмена</a>
{% endblock %}

teacherPlan/templates/teacherPlan/forms/update/7_dif_work_list.html
{% extends 'teacherPlan/pages/template.html' %}
{% block title %}Редактирование сведений о "О работах в интересах вуза"{% endblock %}
{% block pagename %}Редактирование сведений о "О работах в интересах вуза"{% endblock %}
{% block content %}
    <a type="button" href="{% url 'tpplan' planid %}">Назад к плану</a>
        {% if form.errors %}
        <p class="bg-danger text-danger">
            Ошибка при заполнении формы.
        </p>
    {% endif %}

    <form action="#" method="post">
        {% csrf_token %}

        <p><label for="id_work_date">Период:</label>
            <input id="id_work_date" maxlength="20" name="work_date" type="text" value="{{ anotherwork.work_date }}"></p>
        <p><label for="id_type_work">Вид работы:</label>
            <input id="id_type_work" maxlength="200" name="type_work" type="text" value="{{ anotherwork.type_work }}"></p>


        <input type="hidden" name="idaw" value="{{ idaw }}">
        <input type="submit" value="Изменить">
    </form>
    <br>
    <a type="button" class="btn btn-primary" href="{% url 'difWorkList' planid %}">Отмена</a>
{% endblock %}