main/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls import include

admin.autodiscover()
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^teacherPlan/', include('teacherPlan.urls')),
]

teacherPlan/urls.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from django.conf.urls import url, include
from django.contrib.contenttypes import views as contenttype_views
from views import *

urlpatterns = patterns(
   '',
   url(r'^$', index, name='tpindex'),

   #auth
   url(r'^login$', loginTeacher, name='tplogin', ),
   url(r'^loginwitherror$', errorLoginTeacher, name='tploginwitherror', ),
   url(r'^logout$', logoutTeacher, name='tplogout', ),
   url(r'^registerTeacher/', registerTeacher, name='registerTeacher' ),

   #Property
   url('^editProperty/', editPropertySite, name='editProperty'),


   #plans
   url(r'^listOfPlans$', listOfPlans, name='tpplanlist', ),
   url(r'^plan/(?P<id>[0-9a-z]+)$', plan, name='tpplan', ),
   url(r'^currentPlan/', currentPlan, name='currentPlan', ),
   url(r'^plan/add/',makeNewPlan , name='addPlan'),
   url(r'^plan/edit/(?P<id>[0-9a-z]+)$',editPlan , name='editPlan'),
   url(r'^plan/deletePlan/(?P<id>[0-9a-z]+)$',deletePlan , name='deletePlan'),
   url(r'^allplans/', show_all_plan, name='showAllPlans'),



   #forms_edit
   url(r'^studybookList/(?P<id>[0-9a-z]+)/edit', studybook_list_edit, name='studybookListEdit'),
   url(r'^disciplineList/(?P<id>[0-9a-z]+)/edit', discipline_list_edit, name='disciplineListEdit'),
   url(r'^scWorkList/(?P<id>[0-9a-z]+)/edit', scWorkList_edit, name='scWorkListEdit'),
   url(r'^participationList/(?P<id>[0-9a-z]+)/edit', participation_list_edit, name='participationListEdit'),
   url(r'^publicationList/(?P<id>[0-9a-z]+)/edit', publication_list_edit, name='publicationListEdit'),
   url(r'^qualificationList/(?P<id>[0-9a-z]+)/edit', qualification_list_edit, name='qualificationListEdit'),
   url(r'^difWorkList/(?P<id>[0-9a-z]+)/edit', dif_work_list_edit, name='difWorkListEdit'),

   #forms
   url(r'^studybookList/(?P<id>[0-9a-z]+)', studybook_list, name='studybookList'),
   url(r'^disciplineList/(?P<id>[0-9a-z]+)', discipline_list, name='disciplineList'),
   url(r'^scWorkList/(?P<id>[0-9a-z]+)', scWorkList, name='scWorkList'),
   url(r'^participationList/(?P<id>[0-9a-z]+)', participation_list, name='participationList'),
   url(r'^publicationList/(?P<id>[0-9a-z]+)', publication_list, name='publicationList'),
   url(r'^qualificationList/(?P<id>[0-9a-z]+)', qualification_list, name='qualificationList'),
   url(r'^difWorkList/(?P<id>[0-9a-z]+)', dif_work_list, name='difWorkList'),

   url(r'^pdf/(?P<id>[0-9a-z]+)', makePDF, name='pdf'),
)

moevmCommon/models.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.forms import forms
from django.utils.encoding import python_2_unicode_compatible
from djangotoolbox.fields import EmbeddedModelField
from djangotoolbox.fields import ListField


def filter_by_foreign_fields(model_manager, **filter_fields):

    def filter_condition(model):

        if not hasattr(model, 'user'):
            return False

        model_fields = model.__dict__.items()
        user_fields = model.user.__dict__.items()

        # merge model and user field dicts
        fields = dict(model_fields + user_fields +
                      [(k, model_fields[k] + user_fields[k])
                       for k in set(model_fields) & set(user_fields)])

        for arg_name, arg_value in filter_fields.items():
            if arg_name not in fields:
                continue

            if arg_value != fields[arg_name]:
                return False

        return True

    return list(filter(filter_condition, model_manager.all()))

@python_2_unicode_compatible
class UserProfileManager(models.Manager):
    # Для фильтрации по внешнему ключу UserProfile
    #def filter(self, **filter_fields):
    #   return filter_by_foreign_fields(super(UserProfileManager, self), **filter_fields)
    
    def create_all(self, username,
               password, email,
               **kwargs):

        user = User(username=username, email=email, password=password)

        user.first_name = kwargs.get('first_name')
        user.last_name = kwargs.get('last_name')
        user.is_superuser = kwargs.get('is_superuser', False)
        user.save()
        print "hell"
        return self.create(
            user=user,
            patronymic=kwargs.get('patronymic'),
            birth_date=kwargs.get('birth_date'),
            study_group=kwargs.get('study_group'),
            github_id=kwargs.get('github_id'),
            stepic_id=kwargs.get('stepic_id'),
            role=kwargs.get('role', 's'),
            election_date=kwargs.get('election_date'),
            position=kwargs.get('position'),
            contract_date=kwargs.get('contract_date'),
            academic_degree=kwargs.get('academic_degree'),
            year_of_academic_degree=kwargs.get('year_of_academic_degree'),
            academic_status=kwargs.get('academic_status'),
            year_of_academic_status=kwargs.get('year_of_academic_status')
        )

    def create_student(self,
                       username=None,
                       email=None,
                       password=None,
                       first_name=None,
                       last_name=None,
                       birth_date=None,
                       patronymic=None,
                       study_group=None,
                       github_id=None,
                       stepic_id=None,
                       **kwargs):
      user = User(username=username, email=email, password=password)

      user.first_name = first_name
      user.last_name = last_name
      user.is_superuser = False
      user.save()
      type = "s"
      return self.create(
        user=user,
        patronymic=patronymic,
        birth_date=birth_date,
        study_group=study_group,
        github_id=github_id,
        stepic_id=stepic_id,
        type=type
      )

    def create_head_student(self,
                       username=None,
                       email=None,
                       password=None,
                       first_name=None,
                       last_name=None,
                       birth_date=None,
                       patronymic=None,
                       study_group=None,
                       github_id=None,
                       stepic_id=None,
                       **kwargs):
      user = User(username=username, email=email, password=password)
      user.first_name = first_name
      user.last_name = last_name
      user.is_superuser = False
      user.save()
      type = "h"
      return self.create(
        user=user,
        patronymic=patronymic,
        birth_date=birth_date,
        study_group=study_group,
        github_id=github_id,
        stepic_id=stepic_id,
        type=type
      )

    def create_teacher(self,
                       username=None,
                       email=None,
                       password=None,
                       first_name=None,
                       last_name=None,
                       birth_date=None,
                       patronymic=None,
                       election_date=None,
                       position=None,
                       contract_date=None,
                       academic_degree=None,
                       year_of_academic_degree=None,
                       academic_status=None,
                       year_of_academic_status=None,
                       academic_state=None,
                       rate=None,
                       github_id=None,
                       stepic_id=None,
                       **kwargs):
      user = User(username=username, email=email, password=password)
      user.first_name = first_name
      user.last_name = last_name
      user.is_superuser = False
      user.save()
      type = "t"
      return self.create(
        user=user,
        patronymic=patronymic,
        birth_date=birth_date,
        election_date=election_date,
        github_id=github_id,
        stepic_id=stepic_id,
        position=position,
        rate=rate,
        contract_date=contract_date,
        academic_degree=academic_degree,
        year_of_academic_degree=year_of_academic_degree,
        academic_status=academic_status,
        year_of_academic_status=year_of_academic_status,
        academic_state=academic_state,
        type=type
      )


    def create_from_user(self,
                         user=None,
                         position=None,
                         contract_date=None,
                         academic_degree=None,
                         year_of_academic_degree=None,
                         academic_status=None,
                         patronymic=None,
                         **params):
        return  self.create(
            user=user,
            patronymic=patronymic,
            type=type,
            position=position,
            contract_date=contract_date,
            academic_degree=academic_degree,
            year_of_academic_degree=year_of_academic_degree,
            academic_status=academic_status,
        )

    def __str__(self):
      return 'UserProfileManager'

PERSON_TYPE_CHOICES = (
    ('s', 'Студент'),
    ('h', 'Староста'),
    ('t', 'Преподаватель'),
    ('a', 'Администратор'),
)
ACADEMIC_STATUS_CHOICES  = (
  ('a','Ассистент'),
  ('s','Старший преподаватель'),
  ('d','Доцент'),
  ('p','Профессор'),
)
ACADEMIC_DEGREE_CHOICES = (
  ('n','Без степени'),
  ('t','Кандидат наук'),
  ('d','Доктор наук'),
)
ACADEMIC_STATE_CHOICES  = (
  ('a', 'Аспирант'),
  ('d', 'Докторант'),
  ('s', 'Соискатель'),
  ('st', 'Стажер'),
)
RATE_CHOICES = (
    ('1', '0,25 ставки'),
    ('2', '0,5 ставки'),
    ('3', '0,75 ставки'),
    ('4', '1 ставки'),
)

@python_2_unicode_compatible
class UserProfile(models.Model):
    user = models.OneToOneField(
        User,
        verbose_name="Ссылка на аккаунт для авторизации",
    )

    patronymic = models.CharField(
        max_length=30,
        null=True,
        verbose_name="Отчество",
        blank=True,
    )
    birth_date = models.DateField(
        null=True,
        verbose_name="Дата рождения",
        blank=True,
    )
    study_group = models.CharField(
        max_length=5,
        null=True,
        verbose_name="Учебная группа",
        blank=True,
    )
    github_id = models.CharField(
        max_length=100,
        null=True,
        verbose_name="Профиль github",
        blank=True,
    )
    stepic_id = models.CharField(
        max_length=100,
        null=True,
        verbose_name="Профиль stepic",
        blank=True,
    )

    type = models.CharField(
        max_length=2,
        choices=PERSON_TYPE_CHOICES,
        default='s',
        verbose_name="Тип",
    )

    election_date = models.DateField(
        null=True,
        verbose_name="Дата текущего избрания или зачисления на преподавательскую должность",
        blank=True,
    )

    position = models.CharField(
        max_length=40,
        null=True,
        verbose_name="Должность",
        blank=True,
    )

    contract_date = models.DateField(
        null=True,
        blank=True,
        verbose_name="Срок окончания трудового договора",
    )

    academic_degree = models.CharField(
        max_length=1,
        choices=ACADEMIC_DEGREE_CHOICES,
        null=True,
        verbose_name="Ученая степень",
        blank=True,
    )

    year_of_academic_degree = models.IntegerField(
        null=True,
        verbose_name="Год присвоения ученой степени",
        blank=True,
    )

    academic_status = models.CharField(
        max_length=1,
        choices=ACADEMIC_STATUS_CHOICES,
        null=True,
        verbose_name="Учебное звание",
        blank=True,
    )

    year_of_academic_status = models.IntegerField(
        null=True,
        verbose_name="Год получения учебного звания",
        blank=True,
    )

    rate = models.CharField(
        max_length=1,
        choices=RATE_CHOICES,
        null=True,
        verbose_name="Ставка",
        blank=True,
    )

    academic_state = models.CharField(
        max_length=1,
        choices=ACADEMIC_STATE_CHOICES,
        null=True,
        verbose_name="Академическое положение",
        blank=True,
    )

    objects = UserProfileManager()

    @property
    def first_name(self):
        return self.user.first_name

    @property
    def last_name(self):
        return self.user.last_name

    @property
    def login(self):
        return self.user.username

    @property
    def password(self):
        return self.user.password

    @property

teacherPlan/models.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from djangotoolbox.fields import EmbeddedModelField, ListField

@python_2_unicode_compatible
class TeacherSettings(models.Model):
    department_name = models.CharField(
        verbose_name="Название кафедры",
        max_length=10,
        null=True,
        blank=True,
    )
    organisation_name = models.CharField(
        verbose_name="Название факультета",
        max_length=10,
        null=True,
        blank=True,
    )
    department_head = models.CharField(
        verbose_name="Заведующий кафедры",
        max_length=100,
        null=True,
        blank=True,
    )
    organisation_head = models.CharField(
        verbose_name="Декан",
        max_length=100,
        null=True,
        blank=True,
    )
    @staticmethod
    def get():
        try:
            return TeacherSettings.objects.first()
        except:
            return TeacherSettings.objects.create(
                department_name=u"Кафедра",
                organisation_name=u"Факультет",
                department_head=u"Зав. Кафедры",
                organisation_head=u"Декан",
            )

    def __str__(self):
        return u"Основные настройки"

teacherPlan/templates/teacherPlan/full_plan_list.html
{% extends 'teacherPlan/pages/template.html' %}
{% block title %}Список индивидуальных планов преподавателей{% endblock %}
{% block pagename %}Список индивидуальных планов преподавателей{% endblock %}
{% block content %}
    {% if list  %}
        <ul>
        {% for item in list %}
                    <li><a href="{% url 'tpplan' item.id %}">
                        {{ item.person_profile }} ИПП
                        {% if not item.start_date == none  %}
                            на {{  item.start_date }}-{{  item.start_date|add:"1" }} учебный год
                        {% endif %}
                    </a></li>
        {% endfor %}
    </ul>
    {% else %}
        <p>Список пуст</p>
    {% endif %}
{% endblock %}

teacherPlan/templates/teacherPlan/index.html
{% extends 'teacherPlan/pages/template.html' %}
{% block title %}Индивидуальный план преподавателя {% endblock %}
{% block pagename %}Индивидуальный план преподавателя {% endblock %}
{% block content %}

    <p>Добро пожаловать в систему индивидуальных планов кафедры математического обеспечения
        и применения ЭВМ (МО ЭВМ)
    </p>

    {% if not user.is_authenticated %}
        <p><a href="{% url 'tplogin' %}">Для работы в системе необходима авторизация</a></p>
    {% endif %}




{% endblock %}

teacherPlan/templates/teacherPlan/index_main_page.html
<!doctype html>
<html lang="ru-ru">
<head>
    {% load staticfiles %}
    {% url 'studentrecords:login' as login_url %}
    {% url 'studentrecords:logout' as logout_url %}
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Информационная система кафедры МО ЭВМ</title>
    <link href="{% static 'scientificWork/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'teacherPlan/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'scientificWork/css/style.css' %}" rel="stylesheet">
</head>
<body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Навигация</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="/" style="color: gold; font-size: 24px;">МО ЭВМ</a>
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav navbar-right">
                  {% if not user.is_authenticated %}
                    <li><a class="btn" href="{{ login_url }}">Авторизация</a></li>
                  {% else %}
                    <li><a class="btn">Добро пожаловать, {{ user.username }}!</a></li>
                    <li><a class="btn" href="{{ logout_url }}">Выход</a></li>
                  {% endif %}
              </ul>
            </div>
          </div>
        </div>


    <div class="container-fluid">
          <div class="row">
            <div class="col-sm-3 col-md-2 sidebar">
              <ul class="nav nav-sidebar">
                    <li>
                        <a href="/teacherPlan">План преподавателя</a>
                    </li>

                    <li {>
                        <a href="/scientificWork">Научная деятельность</a>
                    </li>

                    <li >
                        <a href="/studentrecords">Работа со студентами</a>
                    </li>
              </ul>
            </div>
            <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
                <h1>Кафедра математического обеспечения и применения ЭВМ</h1>

                <p><em>Рождение</em> кафедры МО ЭВМ в ЛЭТИ на факультете Автоматики и вычислительной техники (ФАВТ) – осень 1978 года.</p>
                    <p><em>Первые студенты</em> – две учебные группы специальности 0647 – «Прикладная математика» - приняты на кафедру летом 1979 года.</p>
                    <p><em>Важная веха</em> в учебно-методической работе кафедры -&nbsp; её активное участие в формировании и подготовке открытия в 1988 году новой специальности «Программное обеспечение вычислительной техники и автоматизированных систем», в рамках которой получают подготовку инженеры-программисты. На базе кафедры был создан Российский научно-методический совет по этой специальности.</p>
                    <p>С 1988 года – подготовка специалистов раздельно по двум специальностям – «Прикладная математика» и «Программное обеспечение вычислительной техники и автоматизированных систем» – &nbsp;позволила кафедре четко расставить акценты в подготовке инженеров-математиков и инженеров-программистов, сохранив при этом общую методическую и кадровую базу, единую профессиональную платформу.</p>
                    <p>С 1996 г. – подготовка по уровневой схеме бакалавров и магистров по направлениям «Прикладная математика и информатика» и «Информатика и вычислительная техника».</p>
                    <p>С 2011 года на кафедру осуществляется прием по направлению «Прикладная математика и информатика», а также по направлению&nbsp;«Программная инженерия», новому для российского высшего профессионального образования.</p>
                    <p>Программная инженерия (SE), как научно-техническая деятельность и образовательное направление:</p>
                    <ul>
                    <li>основывается на математике, информатике и информационных технологиях (computing),</li>
                    <li>занимается разработкой систематических моделей и надежных методов производства высококачественного программного обеспечения.</li>
                    </ul>
                    <p>Выпускники кафедры – профессиональные разработчики программного обеспечения, работающие в ведущих ИТ-компаниях, участвующие в разработке сложных программных продуктов на всех этапах их создания, начиная от математического моделирования, проектирования, разработкой уникальных алгоритмов, заканчивая программной реализацией и тестированием.&nbsp;</p>
                    <p><strong style="font-size: 12px; line-height: 1.5;">Заведующий кафедрой:&nbsp;</strong>Кринкин Кирилл Владимирович, к.т.н.</p>
                    <p><strong>Зам. заведующего по учебной работе:&nbsp;</strong>Лисс Анна Александровна, к.т.н., доцент</p>
                    <p><strong>Зам. заведующего по научной работе:&nbsp;</strong>Яновский Владислав Васильевич, к.т.н., доцент</p>
                    <p><strong>Tel:</strong><span data-mce-mark="1">&nbsp;(812) 234-14-27, (812) 234-26-82</span></p>
                    <p><span data-mce-mark="1"><strong>Email:</strong><span data-mce-mark="1">&nbsp;</span><span data-mce-mark="1">inbox@moevm.info</span></span></p>
            </div>


          </div>
        </div>


</body>
<script src="{% static 'teacherPlan/lib/jquery/dist/jquery.js' %}"></script>
<script src="{% static 'teacherPlan/lib/bootstrap/dist/js/bootstrap.min.js' %}"></script>

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="{% static 'scientificWork/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'scientificWork/js/scripts.js' %}"></script>
</html>

teacherPlan/templates/teacherPlan/login.html
{% extends 'teacherPlan/pages/template.html' %}
{% block title %}Вход на сайт{% endblock %}
{% block pagename %}Вход на сайт{% endblock %}
{% block content %}
    <form role="form" method="post" action="{% url 'tplogin' %}">
        {% csrf_token %}
        <span class="label label-danger">{{ error_message }}</span>
        <br>
        <br>
        <div class="form-group">
            <label for="loginField">Логин</label>
            <input type="text" class="form-control" id="loginField" name="loginField" placeholder="Введите логин">
        </div>
        <div class="form-group">
            <label for="loginField">Пароль</label>
            <input type="password" class="form-control" id="passwordField" name="passwordField" placeholder="Введите пароль">
        </div>
        <button type="submit" class="btn btn-primary">Войти</button>
    </form>
{% endblock %}

teacherPlan/templates/teacherPlan/make_plan.html
{% extends 'teacherPlan/pages/template.html' %}
{% block title %}Создать новый план{% endblock %}
{% block pagename %}Создать новый план{% endblock %}
{% block content %}
    <form action="#" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="hidden" name="user_profile" value="{{ user_profile }}">
        <input type="submit" value="Добавить">
    </form>
{% endblock %}

teacherPlan/templates/teacherPlan/plan.html
{% extends 'teacherPlan/pages/template.html' %}
{% block title %}Индивидуальный план
    {% if not plan.start_date == none  %}
     за {{ plan.start_date }}-{{  plan.start_date|add:"1" }} год.
    {% endif %}
{% endblock %}
{% block pagename %}Индивидуальный план

    {% if not plan.start_date == none %}
     за    {{ plan.start_date }}-{{  plan.start_date|add:"1" }} год.
    {% endif %}
{% endblock %}
{% block content %}
    <h2>Факультет: {{   plan.organisation_name }}</h2>
    <p>Кафедра: {{ plan.department_name }}</p>
    {% if not plan.position == none %}
        <p>Должность: {{ plan.position }}</p>
    {% endif %}
    {% if not plan.last_name == none %}
        <p>Фамилия: {{ plan.last_name }}</p>
    {% endif %}

    {% if not plan.first_name == none %}
        <p>Имя: {{ plan.first_name }}</p>
    {% endif %}

    {% if not plan.patronymic == none %}
        <p>Отчество: {{ plan.patronymic }}</p>
    {% endif %}

    {% if not plan.birth_date == none %}
        <p>Год рождения: {{ plan.birth_date }}</p>
    {% endif %}

    {% if not plan.election_date == none %}
        <p>Дата текущего избрания или зачисления на преподавательскую должность: {{ plan.election_date  }}</p>
    {% endif %}

    {% if not plan.academic_degree == none %}
        <p>Ученая степень и год присуждения: {{ plan.get_academic_degree_display }}
            {{ plan.year_of_academic_degree }}</p>
    {% endif %}
    {% if not plan.academic_status == none %}
        <p>Ученое звание и год присуждения: {{ plan.get_academic_status_display }}
            {{ plan.year_of_academic_status }}</p>
    {% endif %}

    {% if not plan.contract_date == none %}
        <p>Дата переизбрания(окончание трудового договора) : {{ plan.contract_date }}</p>
    {% endif %}

    <h3>Пункты плана:</h3>
    <p><a href="{% url 'studybookList' plan.id %}">Подготовка учебников, учебных пособий и методических указаний,
включая электронные издания</a></p>

    <p><a href="{% url 'disciplineList' plan.id %}">Постановка и модернизация дисциплин</a></p>

    <p><a href="{% url 'scWorkList' plan.id %}">Научно-исследовательская  работа в университете и вне университета</a></p>

    <p><a href="{% url 'participationList' plan.id %}">Участие в конференциях и выставках</a></p>

    <p><a href="{% url 'publicationList' plan.id %}">Список публикаций</a></p>

    <p><a href="{% url 'qualificationList' plan.id %}">Повышение  квалификации</a></p>

    <p><a href="{% url 'difWorkList' plan.id %}">Другие виды работ, выполняемых в интересах университета, факультета и кафедры</a></p>

    <p>
    <form action="{% url 'pdf' plan.id %}" method="get">
        <label for="with_the_cover_page">С титульной страницей
            <input type="checkbox" name="with_the_cover_page">

        </label><br>
        <label for="with_finish_page">С итоговой страницей
            <input type="checkbox" name="with_finish_page">
        </label><br>
        {% csrf_token %}
        <input type="submit" class="btn btn-info" value="Загрузить в PDF"></input>
    </form>

    </p>
    <a href="{% url 'editPlan' plan.id %}" class="btn btn-link">Редактировать ИПП</a>
    <a href="{% url 'deletePlan' plan.id %}" class="btn btn-link">Удалить ИПП</a>

{% endblock %}

teacherPlan/templates/teacherPlan/plan_list.html
{% extends 'teacherPlan/pages/template.html' %}
{% block title %}Список индивидуальных планов{% endblock %}
{% block pagename %}Список индивидуальных планов{% endblock %}
{% block content %}
    {% if list  %}
        <ul>
        {% for item in list %}
                    <li><a href="{% url 'tpplan' item.id %}">
                        ИПП
                        {% if not item.start_date == none  %}
                        на {{  item.start_date }}-{{  item.start_date|add:"1" }} учебный год
                        {% endif %}
                    </a></li>
        {% endfor %}
    </ul>
    {% else %}
        <p>Список пуст</p>
    {% endif %}
{% endblock %}

teacherPlan/templates/teacherPlan/register_teacher.html
{% extends 'teacherPlan/pages/template.html' %}
{% block title %}Регистрация преподавателя{% endblock %}
{% block pagename %}Регистрация преподавателя{% endblock %}
{% block content %}
    {{ message }}
    <form action="#" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Добавить">
    </form>
{% endblock %}